import { getCurrentUser } from 'src/app/redux/users';
import { goToGamesHome } from './../../features/games/redux/games-navigation.actions';
import { HttpCommunicationsService } from '../../core/http-communications/http-communications.service';
import { Injectable } from '@angular/core';
import { Actions, createEffect, ofType } from '@ngrx/effects';
import { retrieveAllGames, initGames, updateGame, editGame, postGame, insertGame } from './games.actions';
import { switchMap, map, concatMap, withLatestFrom } from 'rxjs/operators';
import { Game } from 'src/app/core/model/game.interface';
import { goToDetail } from 'src/app/features/games/redux/games-navigation.actions';
import { Action, select, Store } from '@ngrx/store';
import { Observable, of } from 'rxjs';